# Generated by Django 4.1.5 on 2023-01-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=120)),
                ('productmodel', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
                ('color', models.CharField(max_length=120)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
